### ISSUE TITLE
"No module named numpy"

### ISSUE THREAD

**Issue by HagaiHargil** [napari/magicgui#161]
**Describe the bug**
While trying to run the version in master (which I needed due to the lovely `persist` I received an error that numpy is required but not found.

**To Reproduce**
In a fresh virtualenv containing only the latest magicgui:
```
from magicgui import magicgui


@magicgui
def a(b: str = "1"):
    print("O_O")

a.show(run=True)
```
And when running I get:
```
Traceback (most recent call last):
  File "/home/hagai/Code/magicgui/te.py", line 1, in <module>
    from magicgui import magicgui
  File "/home/hagai/Code/magicgui/magicgui/__init__.py", line 11, in <module>
    from ._magicgui import magic_factory, magicgui
  File "/home/hagai/Code/magicgui/magicgui/_magicgui.py", line 7, in <module>
    from magicgui.widgets import FunctionGui, MainFunctionGui
  File "/home/hagai/Code/magicgui/magicgui/widgets/__init__.py", line 14, in <module>
    from ._bases import Widget, create_widget
  File "/home/hagai/Code/magicgui/magicgui/widgets/_bases/__init__.py", line 46, in <module>
    from .categorical_widget import CategoricalWidget
  File "/home/hagai/Code/magicgui/magicgui/widgets/_bases/categorical_widget.py", line 4, in <module>
    from magicgui.types import ChoicesType
  File "/home/hagai/Code/magicgui/magicgui/types.py", line 10, in <module>
    from magicgui._mpl_image import Colormap, Normalize
  File "/home/hagai/Code/magicgui/magicgui/_mpl_image.py", line 58, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Expected behavior**

Not like this :( although obviously you can't keep master always up and running, so maybe this is one of those days.

**Environment (please complete the following information):**
 - OS: Linux
 - backend: pyqt5
 - magicgui version [e.g. 0.1.0]: latest on master

**Comment by tlambert03** [comment]
thanks!  will fix
