### ISSUE TITLE
Add support for partial/curried functions

### ISSUE THREAD

**Issue by jni** [napari/magicgui#315]
This is standard magicgui and works fine:

```python
from magicgui import magicgui

def add(a: int, b: int) -> int:
    return a + b

gui = magicgui(add, result_widget=True, auto_call=True)
gui.show(run=True)
```

However, if I want to partially run a function before passing it to magicgui, I would normally use `functools.partial` or `toolz.curry`. The first one fails:

```python
from magicgui import magicgui
from functools import partial

def add(a: int, b: int) -> int:
    return a + b

gui = magicgui(functools.partial(add, 5), result_widget=True, auto_call=True)
gui.show(run=True)
```

with:

```pytb
Traceback (most recent call last):
  File "/home/jni/projects/play/magicgui-partial.py", line 7, in <module>
    gui = magicgui(partial(add, 5), result_widget=True, auto_call=True)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 90, in magicgui
    return _magicgui(**locals())
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 246, in _magicgui
    return inner_func(function)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 241, in inner_func
    return magic_class(func, **kwargs)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 156, in __init__
    or f"{function.__module__}.{function.__class__}"
AttributeError: 'functools.partial' object has no attribute '__module__'
```

And the second one:

```python
from magicgui import magicgui
import toolz as tz

@tz.curry
def add(a: int, b: int) -> int:
    return a + b

gui = magicgui(add(5), result_widget=True, auto_call=True)
gui.show(run=True)
```

fails with:

```pytb
Traceback (most recent call last):
  File "/home/jni/projects/play/magicgui-partial.py", line 8, in <module>
    gui = magicgui(add(5), result_widget=True, auto_call=True)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 90, in magicgui
    return _magicgui(**locals())
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 246, in _magicgui
    return inner_func(function)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/_magicgui.py", line 241, in inner_func
    return magic_class(func, **kwargs)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 162, in __init__
    widgets=list(sig.widgets(app).values()),
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/signature.py", line 222, in widgets
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/signature.py", line 222, in <dictcomp>
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/signature.py", line 139, in to_widget
    widget = create_widget(
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_bases/create_widget.py", line 91, in create_widget
    widget = wdg_class(**kwargs)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_concrete.py", line 164, in __init__
    super(cls, self).__init__(**kwargs)
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_bases/ranged_widget.py", line 45, in __init__
    self.value = val
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/magicgui/widgets/_bases/ranged_widget.py", line 57, in value
    if not (self.min <= float(value) <= self.max):
ValueError: could not convert string to float: '__no__default__'
```

**Comment by tlambert03** [comment]
thanks!

**Comment by jni** [comment]
For toolz, I suspect we should sort out exactly what we want to do with the partial function annotations and make an issue/PR in toolz itself. It predates proper function annotations.
